before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: 0jI/GTKRQhaptRT4ZffSwBQv1cof36LtXN6pVUhb5X9U8r/S4SBvOM7j+BUV7Y7oYXx7AD3J43zQgxkRYjSNHl1mBWiy/IOtM7tmNVGKzMGzJtu9xy4C9vs47Kin0rb3ktI85aoa1vS6fbPmFV98OZ/Tl2Nhgv4cNxZrrp28RslXnkaT7uvn50NXlwmyrdKX/WWbtiFs2Eols7qXmzCrf+sUeK+OvXxEIVj6SfkOcNnjIFGWC1IxV2jmGiqsrbwa1qZffeDRO2gzKxpOGM+G65d0Esbg0XzK0WhEggW3XH29MW/bd+nlZnTleD19Z2cUjX0mVCqP95h5xzGAOZ+V766XyIyFUkcDi9M3xcvlqFYsb+9LSyTI2wOO4i2/CpKtnpNVGtGprj7PMfFnOru22kC9xTDdtoJ+I8uNo1BM3HBjLi89Xp3f2Fw/YZRaNOAlHrONCg3cvtbntip6HUjqukKNgpxmTYpqIe5hKhJs6eG1H4waGq2Ur51SFmOQJVZao8jO6mSiw+zPiweRI4JeFcLsc1MhUJ1jeQAWB0Ok/PkZTBLu2/tV0TBU4sFiTG1AFAjtQXw8j3usUGzA+FjY3ZMvjVpm2Vim8iz18gYE+k9qQO9Uusb7S6ggxC78+zzxYl8VNfato8aJVxq778/vOnYydfFSNSKAhJf1JsNiHHM= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
